---
application:
  name: "xuser-api-app"
  project: "xuser-api"
  organization: "QoveryCommunity"
routers:
- name: "main-xuser-api-app"
  routes:
  - application_name: "xuser-api-app"
    paths:
    - "/*"
