version: '2'
services:
  node:
    container_name: ${APP_PREFIX}-node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/home/node/app:delegated
    links:
      - mysql
    ports:
      - 8080

  mysql:
    container_name: ${APP_PREFIX}-mysql
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_PREFIX}
      - MYSQL_USER=${APP_PREFIX}
      - MYSQL_PASSWORD=${APP_PREFIX}
      - MYSQL_DATABASE=${APP_PREFIX}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:delegated
    ports:
      - 33060:3306
